language: rust
rust:
  - 1.27.2
cache:
  - cargo
os:
  - linux
  - osx
script:
  - cargo build --verbose --all
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
